
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psbfggfonamgyxveduex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYmZnZ2ZvbmFtZ3l4dmVkdWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzQ3MTQsImV4cCI6MjA2NDQ1MDcxNH0.4vehMaV86PP5mSD4JWotzgpIOXaFAkNDnjYCzN4TPvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'lovable-app'
    }
  }
});
