// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxatbijsahmmpkoqddbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4YXRiaWpzYWhtbXBrb3FkZGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDA5MjksImV4cCI6MjA2MTc3NjkyOX0.is1ny0sWxEAsokOEvgox4TBYP7UXrk2yYgr9RWrh9tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);